name: Minetest 0.4.16-dev
description: A free, open source voxel game engine and game. Fully extendable. You are in control.
version: 0.4.16-dev
category: Entertainment
maintainer: Vaughan Lapsley <vaughan.lapsley@gmail.com>